{
 "title": "Bird Feeder Monitor",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "feeder", "label": "Feeder", "query": "Feeder1" }
  ]
 },
 "panels": [
  {
   "title": "Count per Perch",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "alias": "#1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_1\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_2\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_3\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#4",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_4\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#5",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_5\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#6",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"count_6\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "count_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    }
   ]
  },
  {
   "title": "Total Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT  sum(\"count_1\") + sum(\"count_2\") + sum(\"count_3\") + sum(\"count_4\") + sum(\"count_5\") + sum(\"count_6\")  FROM \"feeders\" WHERE (\"name\" = 'Feeder1') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"temp\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_1\") + sum(\"time_2\") + sum(\"time_3\") + sum(\"time_4\") + sum(\"time_5\") + sum(\"time_6\") FROM \"feeders\" WHERE (\"name\" = 'Feeder1') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "alias": "Current Temperature",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"temp\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "feeders",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Current Precip Intensity in/hr",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Precipitation Intensity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "select": [
      [
       { "params": [ "precip_Int" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Time on Perch",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Time ms" }
   ],
   "targets": [
    {
     "alias": "#1",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_1\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#2",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_2\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#3",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_3\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#4",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_4\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#5",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_5\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    },
    {
     "alias": "#6",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"time_6\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "time_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Feeder1" }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed and Wind Gust",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "alias": "Speed",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"windspeed\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "windspeed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    },
    {
     "alias": "Gust",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"windgust\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time(5m)",
     "select": [
      [
       { "params": [ "windgust" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Current Cloud Cover",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "Cloud Cover",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "feeders",
     "select": [
      [
       { "params": [ "cloudcover" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  },
  {
   "title": "Current Wind Direction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Wind Direction",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "feeders",
     "query": "SELECT sum(\"winddir\") FROM \"feeders\" WHERE (\"name\" = '$feeder') AND $timeFilter GROUP BY time($interval) ",
     "select": [
      [
       { "params": [ "winddir" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "$feeder" }
     ]
    }
   ]
  }
 ]
}